Repository modern-agile-team/9term-mini-front, pull requests merged in 2025-02, with the labels that each got.

#11 Feature/#2/#3/로그인 회원가입 화면 구현
  insta-clone/src/App.css
  insta-clone/src/index.css
  insta-clone/src/pages/Auth/Login.jsx
  insta-clone/src/pages/Auth/Signup.jsx
  insta-clone/src/pages/Auth/utils.js
  insta-clone/src/utils/isValidEmail.js
Labels: 🎨 Html&css

#10 Feature/#4/home
  insta-clone/src/hooks/useComments.js
  insta-clone/src/hooks/useCurrentUser.js
  insta-clone/src/hooks/useLike.js
  insta-clone/src/index.css
  insta-clone/src/mocks/handlers.js
  insta-clone/src/pages/Home/CommentInput.jsx
  insta-clone/src/pages/Home/Feed.jsx
  insta-clone/src/pages/Home/FeedCard.jsx
  insta-clone/src/pages/Home/Feedlist.jsx
  insta-clone/src/pages/Home/Footer.jsx
  insta-clone/src/pages/Home/Home.jsx
  insta-clone/src/pages/Home/Navbar.jsx
  insta-clone/src/pages/Home/Sidebar.jsx
  insta-clone/src/pages/Posts/CreatePost.jsx
Labels: 🎨 Html&css

#12 🎨 Html&css(#7/upload-post-modal): #7/upload-post-modal
  insta-clone/public/assets/icons/photo.svg
  insta-clone/src/pages/Posts/CreatePost.jsx
Labels: 🎨 Html&css

#16 Refactor/#13/home feedback
  insta-clone/package-lock.json
  insta-clone/package.json
  insta-clone/src/hooks/useComments.js
  insta-clone/src/hooks/useFetchPosts.js
  insta-clone/src/main.jsx
  insta-clone/src/mocks/handlers.js
  insta-clone/src/pages/Auth/Login.jsx
  insta-clone/src/pages/Auth/Signup.jsx
  insta-clone/src/pages/Home/CommentInput.jsx
  insta-clone/src/pages/Home/CommentList.jsx
  insta-clone/src/pages/Home/Feed.jsx
  insta-clone/src/pages/Home/FeedCard.jsx
  insta-clone/src/pages/Home/FeedList.jsx
  insta-clone/src/pages/Home/Navbar.jsx
  insta-clone/src/routes/index.jsx
  insta-clone/src/services/apiClient.js
Labels: 🔨 Refactor

#18 🎨 Html&css(#17): profile.jsx
  insta-clone/package-lock.json
  insta-clone/package.json
  insta-clone/src/main.jsx
  insta-clone/src/mocks/handlers.js
  insta-clone/src/pages/Auth/ProfileModal.jsx
  insta-clone/src/pages/Home/Navbar.jsx
  insta-clone/src/pages/Posts/CreatePostModal.jsx
  insta-clone/src/store/useProfileStore.jsx
  package-lock.json
Labels: 🎨 Html&css

#20 api 연결
  insta-clone/index.html
  insta-clone/src/services/apiClient.js
Labels: 🔨 Refactor

#21 refactor: signup api, utils.js
  insta-clone/src/pages/Auth/Login.jsx
  insta-clone/src/pages/Auth/Signup.jsx
  insta-clone/src/pages/Auth/utils.js
  insta-clone/src/pages/Posts/CreatePostModal.jsx
  insta-clone/src/routes/index.jsx
Labels: 🔨 Refactor

#23 api/#22/posts
  insta-clone/src/hooks/useAuth.js
  insta-clone/src/hooks/useComments.js
  insta-clone/src/hooks/useCurrentUser.js
  insta-clone/src/hooks/useFetchPosts.js
  insta-clone/src/hooks/useLike.js
  insta-clone/src/main.jsx
  insta-clone/src/mocks/handlers.js
  insta-clone/src/pages/Auth/Login.jsx
  insta-clone/src/pages/Auth/ProfileModal.jsx
  insta-clone/src/pages/Home/CommentInput.jsx
  insta-clone/src/pages/Home/CommentList.jsx
  insta-clone/src/pages/Home/FeedCard.jsx
  insta-clone/src/pages/Posts/CreatePostModal.jsx
  insta-clone/src/routes/index.jsx
  insta-clone/src/services/apiClient.js
Labels: 📬 API
